// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EFRepository.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class NestedFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Nested.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Nested", "\tIn order to save nested data into the database\r\n\tAs a programmer\r\n\tI would like " +
                    "to save the data and it\'s child collection into database", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Nested")))
            {
                EFRepository.Tests.NestedFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add two level data into database should be success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Nested")]
        public virtual void AddTwoLevelDataIntoDatabaseShouldBeSuccess()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add two level data into database should be success", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table1.AddRow(new string[] {
                        "1",
                        "TestData"});
#line 7
 testRunner.Given("I have nested datas", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table2.AddRow(new string[] {
                        "1",
                        "Level 2 Data"});
            table2.AddRow(new string[] {
                        "2",
                        "Level 2 Data 2"});
#line 10
 testRunner.And("the nested data with id \"1\" has level 2 data", ((string)(null)), table2, "And ");
#line 14
 testRunner.When("I use generic repository to add data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
 testRunner.And("I save the changes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table3.AddRow(new string[] {
                        "1",
                        "TestData"});
#line 16
 testRunner.Then("database should exists nested datas", ((string)(null)), table3, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table4.AddRow(new string[] {
                        "1",
                        "Level 2 Data"});
            table4.AddRow(new string[] {
                        "2",
                        "Level 2 Data 2"});
#line 19
 testRunner.And("database should exists nested level 2 datas", ((string)(null)), table4, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Update nested data\'s child data which is exists in database should be success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Nested")]
        public virtual void UpdateNestedDataSChildDataWhichIsExistsInDatabaseShouldBeSuccess()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update nested data\'s child data which is exists in database should be success", ((string[])(null)));
#line 24
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table5.AddRow(new string[] {
                        "1",
                        "TestData"});
#line 25
 testRunner.Given("database has nested datas", ((string)(null)), table5, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content",
                        "ParentId"});
            table6.AddRow(new string[] {
                        "1",
                        "Level 2 Data",
                        "1"});
            table6.AddRow(new string[] {
                        "2",
                        "Level 2 Data 2",
                        "1"});
#line 28
 testRunner.And("database has nested level 2 data", ((string)(null)), table6, "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table7.AddRow(new string[] {
                        "1",
                        "TestData"});
#line 32
 testRunner.And("I have nested datas", ((string)(null)), table7, "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content",
                        "ParentId"});
            table8.AddRow(new string[] {
                        "1",
                        "Level 2 Data",
                        "1"});
            table8.AddRow(new string[] {
                        "2",
                        "Level 2 Data 2222",
                        "1"});
#line 35
 testRunner.And("the nested data with id \"1\" has level 2 data", ((string)(null)), table8, "And ");
#line 39
 testRunner.And("Register nested data update hook in generic repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.When("I use generic repository update data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 41
 testRunner.And("I save the changes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table9.AddRow(new string[] {
                        "1",
                        "TestData"});
#line 42
 testRunner.Then("database should exists nested datas", ((string)(null)), table9, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table10.AddRow(new string[] {
                        "1",
                        "Level 2 Data"});
            table10.AddRow(new string[] {
                        "2",
                        "Level 2 Data 2222"});
#line 45
 testRunner.And("database should exists nested level 2 datas", ((string)(null)), table10, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Update nested data\'s with additional child data should be success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Nested")]
        public virtual void UpdateNestedDataSWithAdditionalChildDataShouldBeSuccess()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update nested data\'s with additional child data should be success", ((string[])(null)));
#line 50
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table11.AddRow(new string[] {
                        "1",
                        "TestData"});
#line 51
 testRunner.Given("database has nested datas", ((string)(null)), table11, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content",
                        "ParentId"});
            table12.AddRow(new string[] {
                        "1",
                        "Level 2 Data",
                        "1"});
            table12.AddRow(new string[] {
                        "2",
                        "Level 2 Data 2",
                        "1"});
#line 54
 testRunner.And("database has nested level 2 data", ((string)(null)), table12, "And ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table13.AddRow(new string[] {
                        "1",
                        "TestData"});
#line 58
 testRunner.And("I have nested datas", ((string)(null)), table13, "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content",
                        "ParentId"});
            table14.AddRow(new string[] {
                        "1",
                        "Level 2 Data",
                        "1"});
            table14.AddRow(new string[] {
                        "2",
                        "Level 2 Data 2",
                        "1"});
            table14.AddRow(new string[] {
                        "",
                        "Level 2 Data 3",
                        "1"});
#line 61
 testRunner.And("the nested data with id \"1\" has level 2 data", ((string)(null)), table14, "And ");
#line 66
 testRunner.And("Register nested data update hook in generic repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 67
 testRunner.When("I use generic repository update data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 68
 testRunner.And("I save the changes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table15.AddRow(new string[] {
                        "1",
                        "TestData"});
#line 69
 testRunner.Then("database should exists nested datas", ((string)(null)), table15, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table16.AddRow(new string[] {
                        "1",
                        "Level 2 Data"});
            table16.AddRow(new string[] {
                        "2",
                        "Level 2 Data 2"});
            table16.AddRow(new string[] {
                        "3",
                        "Level 2 Data 3"});
#line 72
 testRunner.And("database should exists nested level 2 datas", ((string)(null)), table16, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Update nested data\'s with two additional child data should be success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Nested")]
        public virtual void UpdateNestedDataSWithTwoAdditionalChildDataShouldBeSuccess()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update nested data\'s with two additional child data should be success", ((string[])(null)));
#line 78
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table17.AddRow(new string[] {
                        "1",
                        "TestData"});
#line 79
 testRunner.Given("database has nested datas", ((string)(null)), table17, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content",
                        "ParentId"});
            table18.AddRow(new string[] {
                        "1",
                        "Level 2 Data",
                        "1"});
            table18.AddRow(new string[] {
                        "2",
                        "Level 2 Data 2",
                        "1"});
#line 82
 testRunner.And("database has nested level 2 data", ((string)(null)), table18, "And ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table19.AddRow(new string[] {
                        "1",
                        "TestData"});
#line 86
 testRunner.And("I have nested datas", ((string)(null)), table19, "And ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content",
                        "ParentId"});
            table20.AddRow(new string[] {
                        "1",
                        "Level 2 Data",
                        "1"});
            table20.AddRow(new string[] {
                        "2",
                        "Level 2 Data 2",
                        "1"});
            table20.AddRow(new string[] {
                        "",
                        "Level 2 Data 3",
                        "1"});
            table20.AddRow(new string[] {
                        "",
                        "Level 2 Data 4",
                        "1"});
#line 89
 testRunner.And("the nested data with id \"1\" has level 2 data", ((string)(null)), table20, "And ");
#line 95
 testRunner.And("Register nested data update hook in generic repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 96
 testRunner.When("I use generic repository update data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 97
 testRunner.And("I save the changes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table21.AddRow(new string[] {
                        "1",
                        "TestData"});
#line 98
 testRunner.Then("database should exists nested datas", ((string)(null)), table21, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table22.AddRow(new string[] {
                        "1",
                        "Level 2 Data"});
            table22.AddRow(new string[] {
                        "2",
                        "Level 2 Data 2"});
            table22.AddRow(new string[] {
                        "3",
                        "Level 2 Data 3"});
            table22.AddRow(new string[] {
                        "4",
                        "Level 2 Data 4"});
#line 101
 testRunner.And("database should exists nested level 2 datas", ((string)(null)), table22, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Update 3 level nested data\'s child data which is exists in database should be suc" +
            "cess")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Nested")]
        public virtual void Update3LevelNestedDataSChildDataWhichIsExistsInDatabaseShouldBeSuccess()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update 3 level nested data\'s child data which is exists in database should be suc" +
                    "cess", ((string[])(null)));
#line 108
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table23.AddRow(new string[] {
                        "1",
                        "TestData"});
#line 109
 testRunner.Given("database has nested datas", ((string)(null)), table23, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content",
                        "ParentId"});
            table24.AddRow(new string[] {
                        "1",
                        "Level 2 Data",
                        "1"});
            table24.AddRow(new string[] {
                        "2",
                        "Level 2 Data 2",
                        "1"});
#line 112
 testRunner.And("database has nested level 2 data", ((string)(null)), table24, "And ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content",
                        "ParentId"});
            table25.AddRow(new string[] {
                        "1",
                        "Level 3 Data",
                        "1"});
            table25.AddRow(new string[] {
                        "2",
                        "Level 3 Data 2",
                        "1"});
#line 116
 testRunner.And("database has nested level 3 data", ((string)(null)), table25, "And ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table26.AddRow(new string[] {
                        "1",
                        "TestData"});
#line 120
 testRunner.And("I have nested datas", ((string)(null)), table26, "And ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content",
                        "ParentId"});
            table27.AddRow(new string[] {
                        "1",
                        "Level 2 Data",
                        "1"});
            table27.AddRow(new string[] {
                        "2",
                        "Level 2 Data 2",
                        "1"});
#line 123
 testRunner.And("the nested data with id \"1\" has level 2 data", ((string)(null)), table27, "And ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content",
                        "ParentId"});
            table28.AddRow(new string[] {
                        "1",
                        "Level 3 Data",
                        "1"});
            table28.AddRow(new string[] {
                        "2",
                        "Level 3 Data 2222",
                        "1"});
#line 127
 testRunner.And("the nested data with id \"1\" and nested level 2 data with id \"1\" has level 3 data", ((string)(null)), table28, "And ");
#line 131
 testRunner.And("Register nested data update hook in generic repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 132
 testRunner.When("I use generic repository update data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 133
 testRunner.And("I save the changes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table29.AddRow(new string[] {
                        "1",
                        "TestData"});
#line 134
 testRunner.Then("database should exists nested datas", ((string)(null)), table29, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table30.AddRow(new string[] {
                        "1",
                        "Level 2 Data"});
            table30.AddRow(new string[] {
                        "2",
                        "Level 2 Data 2"});
#line 137
 testRunner.And("database should exists nested level 2 datas", ((string)(null)), table30, "And ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table31.AddRow(new string[] {
                        "1",
                        "Level 3 Data"});
            table31.AddRow(new string[] {
                        "2",
                        "Level 3 Data 2222"});
#line 141
 testRunner.And("database should exists nested level 3 datas", ((string)(null)), table31, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Update nested data\'s parent data which is exists in database should be success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Nested")]
        public virtual void UpdateNestedDataSParentDataWhichIsExistsInDatabaseShouldBeSuccess()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update nested data\'s parent data which is exists in database should be success", ((string[])(null)));
#line 146
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table32.AddRow(new string[] {
                        "1",
                        "TestData"});
#line 147
 testRunner.Given("database has nested datas", ((string)(null)), table32, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content",
                        "ParentId"});
            table33.AddRow(new string[] {
                        "1",
                        "Level 2 Data",
                        "1"});
            table33.AddRow(new string[] {
                        "2",
                        "Level 2 Data 2",
                        "1"});
#line 150
 testRunner.And("database has nested level 2 data", ((string)(null)), table33, "And ");
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table34.AddRow(new string[] {
                        "1",
                        "TestData Modified"});
#line 154
 testRunner.And("I have nested datas", ((string)(null)), table34, "And ");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content",
                        "ParentId"});
            table35.AddRow(new string[] {
                        "1",
                        "Level 2 Data",
                        "1"});
            table35.AddRow(new string[] {
                        "2",
                        "Level 2 Data 2",
                        "1"});
#line 157
 testRunner.And("the nested data with id \"1\" has level 2 data", ((string)(null)), table35, "And ");
#line 161
 testRunner.And("Register nested data update hook in generic repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 162
 testRunner.When("I use generic repository update data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 163
 testRunner.And("I save the changes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table36.AddRow(new string[] {
                        "1",
                        "TestData Modified"});
#line 164
 testRunner.Then("database should exists nested datas", ((string)(null)), table36, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Content"});
            table37.AddRow(new string[] {
                        "1",
                        "Level 2 Data"});
            table37.AddRow(new string[] {
                        "2",
                        "Level 2 Data 2"});
#line 167
 testRunner.And("database should exists nested level 2 datas", ((string)(null)), table37, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
